/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository of this plugin.
*/
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => LlamaPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/ChatView.ts
var import_obsidian = require("obsidian");
function renderMarkdownCompat(app, source, el, component) {
  try {
    import_obsidian.MarkdownRenderer.render(app, source, el, "", component);
  } catch (e) {
    import_obsidian.MarkdownRenderer.renderMarkdown(source, el, "", component);
  }
}
var LLAMA_CHAT_VIEW_TYPE = "llama-chat-view";
var ChatView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.messages = [];
    this.displayMessages = [];
    this.isStreaming = false;
    this.plugin = plugin;
  }
  getViewType() {
    return LLAMA_CHAT_VIEW_TYPE;
  }
  getDisplayText() {
    return "LLAMA Chat";
  }
  getIcon() {
    return "message-circle";
  }
  async onOpen() {
    this.buildUI();
    await this.checkConnection();
  }
  async onClose() {
    this.plugin.llmClient.abort();
  }
  // ── UI Construction ────────────────────────────────────────────────────────
  buildUI() {
    var _a;
    const root = this.containerEl.children[1];
    root.empty();
    root.addClass("llama-chat-root");
    root.style.padding = "0";
    const header = root.createDiv("llama-header");
    const titleRow = header.createDiv("llama-header-title-row");
    const icon = titleRow.createSpan("llama-header-icon");
    icon.textContent = "\u{1F999}";
    titleRow.createSpan("llama-header-title").textContent = "LLAMA Chat";
    const statusRow = header.createDiv("llama-header-status-row");
    this.statusDot = statusRow.createSpan("llama-status-dot");
    this.statusLabel = statusRow.createSpan("llama-status-label");
    this.statusLabel.textContent = "Connecting\u2026";
    this.noteCountEl = statusRow.createSpan("llama-note-count");
    const headerActions = header.createDiv("llama-header-actions");
    const refreshBtn = headerActions.createEl("button", { cls: "llama-icon-btn", title: "Check connection" });
    (0, import_obsidian.setIcon)(refreshBtn, "refresh-cw");
    refreshBtn.addEventListener("click", () => this.checkConnection());
    const clearBtn = headerActions.createEl("button", { cls: "llama-icon-btn", title: "Clear chat" });
    (0, import_obsidian.setIcon)(clearBtn, "trash-2");
    clearBtn.addEventListener("click", () => this.clearChat());
    const undoBtn = headerActions.createEl("button", { cls: "llama-icon-btn", title: "Undo last AI edit" });
    (0, import_obsidian.setIcon)(undoBtn, "rotate-ccw");
    undoBtn.addEventListener("click", () => this.undoLastEdit());
    const settingsBtn = headerActions.createEl("button", { cls: "llama-icon-btn", title: "Plugin settings" });
    (0, import_obsidian.setIcon)(settingsBtn, "settings");
    settingsBtn.addEventListener("click", () => {
      this.app.setting.open();
      this.app.setting.openTabById("obsidian-llama-chat");
    });
    this.messagesContainer = root.createDiv("llama-messages");
    this.renderWelcome();
    const inputBar = root.createDiv("llama-input-bar");
    this.inputArea = inputBar.createEl("textarea", {
      cls: "llama-input",
      attr: { placeholder: "Ask anything about your vault\u2026", rows: "1" }
    });
    this.inputArea.addEventListener("input", () => {
      this.inputArea.style.height = "auto";
      this.inputArea.style.height = Math.min(this.inputArea.scrollHeight, 160) + "px";
    });
    this.inputArea.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        if (!this.isStreaming)
          this.sendMessage();
      }
    });
    const btnGroup = inputBar.createDiv("llama-btn-group");
    this.sendBtn = btnGroup.createEl("button", { cls: "llama-send-btn", text: "Send" });
    (0, import_obsidian.setIcon)(this.sendBtn, "send");
    this.sendBtn.addEventListener("click", () => this.sendMessage());
    this.stopBtn = btnGroup.createEl("button", { cls: "llama-stop-btn", text: "Stop" });
    (0, import_obsidian.setIcon)(this.stopBtn, "square");
    this.stopBtn.style.display = "none";
    this.stopBtn.addEventListener("click", () => {
      this.plugin.llmClient.abort();
      this.setStreaming(false);
    });
    const footer = root.createDiv("llama-footer");
    const permBadge = footer.createSpan("llama-perm-badge");
    const permIcons = {
      read_only: "\u{1F50D} Read only",
      read_append: "\u270F\uFE0F Read + Append",
      full_edit: "\u26A0\uFE0F Full edit"
    };
    permBadge.textContent = (_a = permIcons[this.plugin.settings.editPermission]) != null ? _a : "?";
    permBadge.title = "Vault edit permission level \u2014 change in settings";
    const modelBadge = footer.createSpan("llama-model-badge");
    modelBadge.textContent = this.plugin.settings.model || "auto model";
  }
  // ── Connection Check ───────────────────────────────────────────────────────
  async checkConnection() {
    this.setStatus("connecting");
    try {
      const model = await this.plugin.llmClient.healthCheck();
      this.setStatus("connected", model);
    } catch (e) {
      this.setStatus("error", e.message);
    }
    if (this.plugin.indexer.isReady) {
      this.noteCountEl.textContent = `${this.plugin.indexer.noteCount} notes indexed`;
    } else {
      this.noteCountEl.textContent = "Indexing\u2026";
    }
  }
  setStatus(state, info) {
    this.statusDot.className = `llama-status-dot llama-status-${state}`;
    if (state === "connected") {
      this.statusLabel.textContent = info ? `Connected \xB7 ${info}` : "Connected";
    } else if (state === "error") {
      this.statusLabel.textContent = `Offline \xB7 ${info != null ? info : ""}`;
    } else {
      this.statusLabel.textContent = "Connecting\u2026";
    }
  }
  // ── Sending Messages ───────────────────────────────────────────────────────
  async sendMessage() {
    const text = this.inputArea.value.trim();
    if (!text || this.isStreaming)
      return;
    this.inputArea.value = "";
    this.inputArea.style.height = "auto";
    this.displayMessages.push({ role: "user", content: text });
    this.messages.push({ role: "user", content: text });
    this.renderMessages();
    this.setStreaming(true);
    const enrichedMessages = await this.plugin.contextBuilder.prependSystemMessage(
      this.messages.slice(0, -1),
      // all except the just-added user msg (context builder handles it)
      text
    );
    enrichedMessages.push({ role: "user", content: text });
    const assistantDisplay = { role: "assistant", content: "", streaming: true, toolEvents: [] };
    this.displayMessages.push(assistantDisplay);
    this.renderMessages();
    let finalMessages = enrichedMessages;
    const onChunk = (chunk) => {
      if (chunk.type === "token" && chunk.content) {
        assistantDisplay.content += chunk.content;
        this.updateLastBubble(assistantDisplay);
      } else if (chunk.type === "tool_start") {
        assistantDisplay.toolEvents.push({ type: "start", name: chunk.toolName });
        this.updateLastBubble(assistantDisplay);
      } else if (chunk.type === "tool_end") {
        const evList = assistantDisplay.toolEvents;
        let last;
        for (let i = evList.length - 1; i >= 0; i--) {
          if (evList[i].name === chunk.toolName && evList[i].type === "start") {
            last = evList[i];
            break;
          }
        }
        if (!last && evList.length > 0)
          last = evList[evList.length - 1];
        if (last) {
          last.type = "end";
          last.result = chunk.toolResult;
        }
        this.updateLastBubble(assistantDisplay);
      } else if (chunk.type === "error" && chunk.error) {
        assistantDisplay.content = chunk.error;
        assistantDisplay.role = "error";
        this.updateLastBubble(assistantDisplay);
      } else if (chunk.type === "done") {
        assistantDisplay.streaming = false;
        this.updateLastBubble(assistantDisplay);
      }
    };
    try {
      const gen = this.plugin.llmClient.runTurn(enrichedMessages, this.plugin.toolExecutor, onChunk);
      for await (const msgs of gen) {
        finalMessages = msgs;
      }
    } catch (e) {
      assistantDisplay.content = `Error: ${e.message}`;
      assistantDisplay.role = "error";
      assistantDisplay.streaming = false;
      this.updateLastBubble(assistantDisplay);
    }
    this.messages = finalMessages.filter((m) => m.role !== "system");
    this.setStreaming(false);
    this.scrollToBottom();
  }
  // ── Rendering ─────────────────────────────────────────────────────────────
  editMessage(msg) {
    const idx = this.displayMessages.indexOf(msg);
    if (idx === -1)
      return;
    let userCount = 0;
    for (let i = 0; i < idx; i++) {
      if (this.displayMessages[i].role === "user")
        userCount++;
    }
    let mIdx = -1;
    let mUserCount = 0;
    for (let i = 0; i < this.messages.length; i++) {
      if (this.messages[i].role === "user") {
        if (mUserCount === userCount) {
          mIdx = i;
          break;
        }
        mUserCount++;
      }
    }
    if (mIdx !== -1) {
      this.messages = this.messages.slice(0, mIdx);
    }
    this.displayMessages = this.displayMessages.slice(0, idx);
    this.inputArea.value = msg.content;
    this.inputArea.focus();
    this.inputArea.style.height = "auto";
    this.inputArea.style.height = this.inputArea.scrollHeight + "px";
    this.renderMessages();
  }
  renderWelcome() {
    const welcome = this.messagesContainer.createDiv("llama-welcome");
    welcome.createEl("div", { cls: "llama-welcome-emoji", text: "\u{1F999}" });
    welcome.createEl("div", { cls: "llama-welcome-title", text: "LLAMA Chat" });
    welcome.createEl("div", {
      cls: "llama-welcome-subtitle",
      text: "Your local AI assistant with full vault access"
    });
    const chips = welcome.createDiv("llama-welcome-chips");
    const examples = [
      "\u{1F50D} Search my notes on machine learning",
      "\u{1F4DD} Summarize my recent todos",
      "\u270F\uFE0F Add a section to my README",
      "\u{1F4C1} List what's in my Projects folder"
    ];
    for (const ex of examples) {
      const chip = chips.createEl("button", { cls: "llama-example-chip", text: ex });
      chip.addEventListener("click", () => {
        this.inputArea.value = ex.slice(2).trim();
        this.inputArea.focus();
      });
    }
  }
  renderMessages() {
    this.messagesContainer.empty();
    if (this.displayMessages.length === 0) {
      this.renderWelcome();
      return;
    }
    for (const msg of this.displayMessages) {
      this.renderBubble(msg, this.messagesContainer);
    }
    this.scrollToBottom();
  }
  renderBubble(msg, container) {
    var _a;
    const wrapper = container.createDiv(`llama-msg-wrapper llama-msg-${msg.role}`);
    const avatar = wrapper.createDiv("llama-avatar");
    avatar.textContent = msg.role === "user" ? "\u{1F464}" : msg.role === "error" ? "\u26A0\uFE0F" : "\u{1F999}";
    const bubble = wrapper.createDiv("llama-bubble");
    if (msg.toolEvents && msg.toolEvents.length > 0) {
      const toolsEl = bubble.createDiv("llama-tool-events");
      for (const ev of msg.toolEvents) {
        const evEl = toolsEl.createDiv(`llama-tool-event llama-tool-${ev.type}`);
        const icons = {
          search_vault: "\u{1F50D}",
          read_note: "\u{1F4D6}",
          list_folder: "\u{1F4C1}",
          append_to_note: "\u270F\uFE0F",
          edit_note: "\u270F\uFE0F",
          create_note: "\u{1F4C4}"
        };
        const icon = (_a = icons[ev.name]) != null ? _a : "\u{1F6E0}\uFE0F";
        if (ev.type === "start") {
          evEl.textContent = `${icon} ${ev.name.replace(/_/g, " ")}\u2026`;
        } else {
          const summary = ev.result ? ev.result.length > 80 ? ev.result.slice(0, 80) + "\u2026" : ev.result : "done";
          evEl.textContent = `${icon} ${ev.name.replace(/_/g, " ")}: ${summary}`;
        }
      }
    }
    const contentEl = bubble.createDiv("llama-bubble-content");
    if (msg.content) {
      renderMarkdownCompat(this.app, msg.content, contentEl, this);
    }
    if (msg.streaming) {
      const cursor = bubble.createSpan("llama-cursor");
      cursor.textContent = "\u258B";
    }
    if (!msg.streaming && msg.role !== "error") {
      const actions = wrapper.createDiv("llama-msg-actions");
      const copyBtn = actions.createEl("button", { cls: "llama-msg-action-btn", title: "Copy" });
      (0, import_obsidian.setIcon)(copyBtn, "copy");
      copyBtn.addEventListener("click", () => {
        navigator.clipboard.writeText(msg.content);
        (0, import_obsidian.setIcon)(copyBtn, "check");
        setTimeout(() => (0, import_obsidian.setIcon)(copyBtn, "copy"), 2e3);
      });
      if (msg.role === "user") {
        const editBtn = actions.createEl("button", { cls: "llama-msg-action-btn", title: "Edit & Resend" });
        (0, import_obsidian.setIcon)(editBtn, "pencil");
        editBtn.addEventListener("click", () => this.editMessage(msg));
      }
    }
    return wrapper;
  }
  updateLastBubble(msg) {
    const wrappers = this.messagesContainer.querySelectorAll(".llama-msg-wrapper");
    const last = wrappers[wrappers.length - 1];
    if (last) {
      const newEl = document.createElement("div");
      this.renderBubble(msg, newEl);
      last.replaceWith(newEl.firstChild);
    }
    this.scrollToBottom();
  }
  scrollToBottom() {
    requestAnimationFrame(() => {
      this.messagesContainer.scrollTop = this.messagesContainer.scrollHeight;
    });
  }
  // ── Actions ────────────────────────────────────────────────────────────────
  clearChat() {
    this.messages = [];
    this.displayMessages = [];
    this.renderMessages();
  }
  async undoLastEdit() {
    const path = await this.plugin.toolExecutor.undoLast();
    if (path) {
      new import_obsidian.Notice(`\u21A9\uFE0F Undid last AI edit to "${path}"`);
    } else {
      new import_obsidian.Notice("Nothing to undo");
    }
  }
  setStreaming(streaming) {
    this.isStreaming = streaming;
    this.sendBtn.style.display = streaming ? "none" : "flex";
    this.stopBtn.style.display = streaming ? "flex" : "none";
    this.inputArea.disabled = streaming;
    if (!streaming) {
      this.inputArea.focus();
    }
  }
};

// src/indexer.ts
var import_obsidian2 = require("obsidian");
var INDEX_VERSION = 2;
var LRU_MAX = 100;
function globToRegex(pattern) {
  const escaped = pattern.replace(/[.+^${}()|[\]\\]/g, "\\$&").replace(/\*\*/g, "<<<DS>>>").replace(/\*/g, "[^/]*").replace(/<<<DS>>>/g, ".*");
  return new RegExp(`^${escaped}$`);
}
var LRUCache = class {
  constructor(max) {
    this.max = max;
    this.map = /* @__PURE__ */ new Map();
  }
  get(key) {
    if (!this.map.has(key))
      return void 0;
    const val = this.map.get(key);
    this.map.delete(key);
    this.map.set(key, val);
    return val;
  }
  set(key, value) {
    if (this.map.has(key))
      this.map.delete(key);
    else if (this.map.size >= this.max) {
      const firstKey = this.map.keys().next().value;
      if (firstKey !== void 0)
        this.map.delete(firstKey);
    }
    this.map.set(key, value);
  }
  delete(key) {
    this.map.delete(key);
  }
  clear() {
    this.map.clear();
  }
};
var VaultIndexer = class {
  constructor(app, settings) {
    this.app = app;
    this.settings = settings;
    this.index = { version: INDEX_VERSION, buildTime: 0, notes: {} };
    this.contentCache = new LRUCache(LRU_MAX);
    this.excludeRegexes = [];
    this.ready = false;
    this.rebuildExcludeRegexes();
  }
  // ── Public API ────────────────────────────────────────────────────────────
  get isReady() {
    return this.ready;
  }
  get noteCount() {
    return Object.keys(this.index.notes).length;
  }
  get excludedCount() {
    return this.app.vault.getMarkdownFiles().filter((f) => this.isExcluded(f.path)).length;
  }
  /** Build the index on plugin startup */
  async build(savedData) {
    this.rebuildExcludeRegexes();
    const files = this.app.vault.getMarkdownFiles();
    const needsRebuild = !savedData || savedData.version !== INDEX_VERSION || // Check if any file has changed since the last index
    files.some((f) => {
      const meta = savedData.notes[f.path];
      return !meta || meta.mtime !== f.stat.mtime;
    });
    if (!needsRebuild && savedData) {
      this.index = savedData;
      const currentPaths = new Set(files.map((f) => f.path));
      for (const path of Object.keys(this.index.notes)) {
        if (!currentPaths.has(path))
          delete this.index.notes[path];
      }
      this.ready = true;
      return;
    }
    this.index = { version: INDEX_VERSION, buildTime: Date.now(), notes: {} };
    const CHUNK = 50;
    for (let i = 0; i < files.length; i += CHUNK) {
      const chunk = files.slice(i, i + CHUNK);
      for (const file of chunk) {
        if (!this.isExcluded(file.path)) {
          this.index.notes[file.path] = await this.buildMeta(file);
        }
      }
      await new Promise((r) => setTimeout(r, 0));
    }
    this.ready = true;
  }
  /** Update a single file in the index */
  async updateFile(file) {
    if (this.isExcluded(file.path)) {
      delete this.index.notes[file.path];
    } else {
      this.index.notes[file.path] = await this.buildMeta(file);
    }
    this.contentCache.delete(file.path);
  }
  /** Remove a file from the index */
  removeFile(path) {
    delete this.index.notes[path];
    this.contentCache.delete(path);
  }
  /** Rename a file in the index */
  async renameFile(file, oldPath) {
    this.removeFile(oldPath);
    await this.updateFile(file);
  }
  /** Get the serialisable index to persist */
  getSerializable() {
    return this.index;
  }
  /** Update settings (e.g. exclusion patterns changed) */
  updateSettings(settings) {
    this.settings = settings;
    this.rebuildExcludeRegexes();
  }
  // ── Content Access ────────────────────────────────────────────────────────
  /** Read the full content of a note (with LRU cache) */
  async readNote(path) {
    const cached = this.contentCache.get(path);
    if (cached !== void 0)
      return cached;
    const file = this.app.vault.getAbstractFileByPath(path);
    if (!(file instanceof import_obsidian2.TFile))
      return null;
    if (this.isExcluded(path))
      return null;
    const content = await this.app.vault.read(file);
    this.contentCache.set(path, content);
    return content;
  }
  // ── Search ────────────────────────────────────────────────────────────────
  /**
   * Search vault notes.
   * @param query   Free-text query (scored against title + tags + frontmatter)
   * @param tags    Optional tag filter (must match any)
   * @param limit   Max results to return
   */
  search(query, tags, limit = 20) {
    const q = query.toLowerCase().trim();
    const results = [];
    for (const [, meta] of Object.entries(this.index.notes)) {
      let score = 0;
      if (tags && tags.length > 0) {
        const noteTags = meta.tags.map((t) => t.toLowerCase());
        const match = tags.some((tag) => noteTags.some((nt) => nt.includes(tag.toLowerCase())));
        if (!match)
          continue;
        score += 5;
      }
      if (q) {
        const titleLower = meta.title.toLowerCase();
        const pathLower = meta.path.toLowerCase();
        if (titleLower === q)
          score += 100;
        else if (titleLower.startsWith(q))
          score += 50;
        else if (titleLower.includes(q))
          score += 20;
        if (pathLower.includes(q))
          score += 10;
        for (const tag of meta.tags) {
          if (tag.toLowerCase().includes(q))
            score += 8;
        }
        const fmStr = JSON.stringify(meta.frontmatter).toLowerCase();
        if (fmStr.includes(q))
          score += 3;
        const words = q.split(/\s+/).filter((w) => w.length > 2);
        for (const word of words) {
          if (titleLower.includes(word))
            score += 5;
          if (pathLower.includes(word))
            score += 2;
        }
        if (score === 0)
          continue;
      } else {
        score = meta.mtime;
      }
      results.push({ path: meta.path, title: meta.title, tags: meta.tags, score });
    }
    return results.sort((a, b) => b.score - a.score).slice(0, limit);
  }
  /** Full-text search (reads file content — expensive) */
  async fullTextSearch(query, limit = 10) {
    const q = query.toLowerCase().trim();
    if (!q)
      return [];
    const candidates = Object.keys(this.index.notes);
    const results = [];
    for (const path of candidates) {
      const content = await this.readNote(path);
      if (!content)
        continue;
      const lower = content.toLowerCase();
      const idx = lower.indexOf(q);
      if (idx === -1)
        continue;
      const start = Math.max(0, idx - 60);
      const end = Math.min(content.length, idx + q.length + 60);
      const snippet = "..." + content.slice(start, end).replace(/\n/g, " ").trim() + "...";
      const occurrences = (lower.match(new RegExp(q.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), "g")) || []).length;
      results.push({
        path,
        title: this.index.notes[path].title,
        tags: this.index.notes[path].tags,
        snippet,
        score: occurrences
      });
    }
    return results.sort((a, b) => b.score - a.score).slice(0, limit);
  }
  /** Get all notes in a folder */
  listFolder(folderPath) {
    const normalized = folderPath.replace(/\/$/, "");
    return Object.values(this.index.notes).filter((meta) => {
      const dir = meta.path.includes("/") ? meta.path.substring(0, meta.path.lastIndexOf("/")) : "";
      return normalized === "" ? !meta.path.includes("/") : dir === normalized || dir.startsWith(normalized + "/");
    });
  }
  /** Get the compact vault map string for injection into system prompt */
  getVaultMap() {
    const notes = Object.values(this.index.notes);
    const lines = notes.map((meta) => {
      const tags = meta.tags.length > 0 ? ` [${meta.tags.join(", ")}]` : "";
      return `- ${meta.path}${tags}`;
    });
    return lines.join("\n");
  }
  /** Get top N notes ranked by relevance to a query (for auto-injection) */
  getTopNotes(query, n) {
    const results = this.search(query, void 0, n);
    return results.map((r) => this.index.notes[r.path]).filter(Boolean);
  }
  /** Get note metadata by path */
  getNoteMeta(path) {
    var _a;
    return (_a = this.index.notes[path]) != null ? _a : null;
  }
  // ── Private Helpers ───────────────────────────────────────────────────────
  isExcluded(path) {
    return this.excludeRegexes.some((re) => re.test(path));
  }
  rebuildExcludeRegexes() {
    this.excludeRegexes = this.settings.excludePatterns.map(globToRegex);
  }
  async buildMeta(file) {
    var _a, _b;
    const cache = this.app.metadataCache.getFileCache(file);
    const tags = cache ? (_a = (0, import_obsidian2.getAllTags)(cache)) != null ? _a : [] : [];
    const frontmatter = (_b = cache == null ? void 0 : cache.frontmatter) != null ? _b : {};
    const wordCount = Math.round(file.stat.size / 5);
    return {
      path: file.path,
      title: file.basename,
      tags,
      frontmatter,
      mtime: file.stat.mtime,
      wordCount,
      size: file.stat.size
    };
  }
};

// src/tools.ts
var import_obsidian3 = require("obsidian");
var TOOL_DEFINITIONS = [
  {
    type: "function",
    function: {
      name: "search_vault",
      description: "Search notes in the Obsidian vault by keyword, title, or tags. Returns a list of matching note paths with metadata.",
      parameters: {
        type: "object",
        properties: {
          query: {
            type: "string",
            description: "Search terms (matched against title, tags, and frontmatter)"
          },
          tags: {
            type: "array",
            items: { type: "string" },
            description: "Optional: filter results to notes containing any of these tags (without #)"
          },
          full_text: {
            type: "boolean",
            description: "If true, also searches inside file content (slower but finds more results)"
          },
          limit: {
            type: "number",
            description: "Maximum number of results to return (default 10)"
          }
        },
        required: ["query"]
      }
    }
  },
  {
    type: "function",
    function: {
      name: "read_note",
      description: "Read the full Markdown content of a note by its vault path.",
      parameters: {
        type: "object",
        properties: {
          path: {
            type: "string",
            description: 'The vault-relative path to the note, e.g. "Projects/MyNote.md"'
          }
        },
        required: ["path"]
      }
    }
  },
  {
    type: "function",
    function: {
      name: "list_folder",
      description: "List all notes inside a vault folder (and its sub-folders).",
      parameters: {
        type: "object",
        properties: {
          path: {
            type: "string",
            description: 'Folder path, e.g. "Projects" or "" for vault root'
          }
        },
        required: ["path"]
      }
    }
  },
  {
    type: "function",
    function: {
      name: "append_to_note",
      description: "Append text to the end of an existing note. This is the safest way to add content.",
      parameters: {
        type: "object",
        properties: {
          path: { type: "string", description: "Vault-relative path to the note" },
          content: { type: "string", description: "Text to append (Markdown)" }
        },
        required: ["path", "content"]
      }
    }
  },
  {
    type: "function",
    function: {
      name: "edit_note",
      description: "Edit a note by replacing a specific block of text (surgical) or overwriting the entire content (full_overwrite). Prefer replace_block for precision.",
      parameters: {
        type: "object",
        properties: {
          path: { type: "string", description: "Vault-relative path to the note" },
          mode: {
            type: "string",
            enum: ["replace_block", "full_overwrite"],
            description: '"replace_block" finds old_text and replaces it with new_text. "full_overwrite" replaces the entire note content with new_content.'
          },
          old_text: {
            type: "string",
            description: "The exact text to find and replace (required for replace_block mode)"
          },
          new_text: {
            type: "string",
            description: "The replacement text (required for replace_block mode)"
          },
          new_content: {
            type: "string",
            description: "The full new content for the note (required for full_overwrite mode)"
          }
        },
        required: ["path", "mode"]
      }
    }
  },
  {
    type: "function",
    function: {
      name: "create_note",
      description: "Create a new note at the given path with specified content.",
      parameters: {
        type: "object",
        properties: {
          path: {
            type: "string",
            description: 'Vault-relative path including filename, e.g. "Projects/NewNote.md"'
          },
          content: { type: "string", description: "Initial Markdown content of the new note" },
          overwrite: {
            type: "boolean",
            description: "If true, overwrite if the file already exists. Default false."
          }
        },
        required: ["path", "content"]
      }
    }
  }
];
var TOOL_INJECTION_PROMPT = `
You have access to the following vault tools. When you need to use a tool, output ONLY a JSON block wrapped in <tool_call> tags, then stop and wait for the result. Do not output anything else on the same line.

Available tools:
- search_vault(query, tags?, full_text?, limit?): Search notes by keyword/tag
- read_note(path): Read full content of a note
- list_folder(path): List notes in a folder
- append_to_note(path, content): Append text to a note
- edit_note(path, mode, old_text?, new_text?, new_content?): Edit a note
- create_note(path, content, overwrite?): Create a new note

Format:
<tool_call>
{"name": "tool_name", "arguments": {"arg": "value"}}
</tool_call>
`.trim();
var ToolExecutor = class {
  constructor(app, indexer, settings) {
    this.app = app;
    this.indexer = indexer;
    this.settings = settings;
    this.undoStack = [];
  }
  updateSettings(settings) {
    this.settings = settings;
  }
  /** Execute a tool call and return the result as a string */
  async execute(name, argsJson) {
    let args;
    try {
      args = JSON.parse(argsJson);
    } catch (e) {
      return `Error: Invalid JSON arguments: ${argsJson}`;
    }
    try {
      switch (name) {
        case "search_vault":
          return await this.toolSearchVault(args);
        case "read_note":
          return await this.toolReadNote(args);
        case "list_folder":
          return await this.toolListFolder(args);
        case "append_to_note":
          return await this.toolAppendToNote(args);
        case "edit_note":
          return await this.toolEditNote(args);
        case "create_note":
          return await this.toolCreateNote(args);
        default:
          return `Error: Unknown tool "${name}"`;
      }
    } catch (e) {
      return `Error: ${e instanceof Error ? e.message : String(e)}`;
    }
  }
  get undoHistory() {
    return [...this.undoStack];
  }
  async undoLast() {
    const entry = this.undoStack.pop();
    if (!entry)
      return null;
    const file = this.app.vault.getAbstractFileByPath(entry.path);
    if (file instanceof import_obsidian3.TFile) {
      await this.app.vault.modify(file, entry.previousContent);
      await this.indexer.updateFile(file);
      return entry.path;
    }
    return null;
  }
  // ── Tools ─────────────────────────────────────────────────────────────────
  async toolSearchVault(args) {
    var _a;
    const query = String((_a = args.query) != null ? _a : "");
    const tags = Array.isArray(args.tags) ? args.tags.map(String) : void 0;
    const fullText = Boolean(args.full_text);
    const limit = typeof args.limit === "number" ? Math.min(args.limit, 50) : 10;
    const metaResults = this.indexer.search(query, tags, limit);
    if (fullText && query) {
      const ftResults = await this.indexer.fullTextSearch(query, limit);
      const existing = new Set(metaResults.map((r) => r.path));
      for (const r of ftResults) {
        if (!existing.has(r.path))
          metaResults.push(r);
      }
    }
    if (metaResults.length === 0)
      return "No notes found matching your search.";
    const lines = metaResults.slice(0, limit).map((r) => {
      const tags2 = r.tags.length > 0 ? ` [${r.tags.join(", ")}]` : "";
      const snippet = r.snippet ? `
  > ${r.snippet}` : "";
      return `- ${r.path}${tags2}${snippet}`;
    });
    return `Found ${metaResults.length} notes:
${lines.join("\n")}`;
  }
  async toolReadNote(args) {
    const path = this.validatePath(args.path);
    if (!path)
      return "Error: Invalid or missing path";
    const content = await this.indexer.readNote(path);
    if (content === null)
      return `Error: Note not found or excluded: ${path}`;
    return `Content of "${path}":

${content}`;
  }
  toolListFolder(args) {
    var _a;
    const path = String((_a = args.path) != null ? _a : "").trim();
    const notes = this.indexer.listFolder(path);
    if (notes.length === 0)
      return `No notes found in folder: "${path || "vault root"}"`;
    const lines = notes.map((m) => {
      const tags = m.tags.length > 0 ? ` [${m.tags.join(", ")}]` : "";
      return `- ${m.path}${tags}`;
    });
    return `${notes.length} notes in "${path || "vault root"}":
${lines.join("\n")}`;
  }
  async toolAppendToNote(args) {
    var _a;
    if (this.settings.editPermission === "read_only") {
      return "Error: Edit permission is set to read-only. Change it in plugin settings.";
    }
    const path = this.validatePath(args.path);
    if (!path)
      return "Error: Invalid or missing path";
    const content = String((_a = args.content) != null ? _a : "");
    if (!content.trim())
      return "Error: Content to append is empty";
    const file = this.app.vault.getAbstractFileByPath(path);
    if (!(file instanceof import_obsidian3.TFile))
      return `Error: Note not found: ${path}`;
    const existing = await this.app.vault.read(file);
    this.pushUndo(path, existing, `append to ${path}`);
    const separator = existing.endsWith("\n") ? "\n" : "\n\n";
    await this.app.vault.modify(file, existing + separator + content);
    await this.indexer.updateFile(file);
    return `\u2705 Appended ${content.length} chars to "${path}"`;
  }
  async toolEditNote(args) {
    var _a, _b, _c, _d;
    if (this.settings.editPermission === "read_only") {
      return "Error: Edit permission is set to read-only. Change it in plugin settings.";
    }
    const path = this.validatePath(args.path);
    if (!path)
      return "Error: Invalid or missing path";
    const mode = String((_a = args.mode) != null ? _a : "");
    const file = this.app.vault.getAbstractFileByPath(path);
    if (!(file instanceof import_obsidian3.TFile))
      return `Error: Note not found: ${path}`;
    const existing = await this.app.vault.read(file);
    this.pushUndo(path, existing, `edit ${path} (${mode})`);
    if (mode === "replace_block") {
      const oldText = String((_b = args.old_text) != null ? _b : "");
      const newText = String((_c = args.new_text) != null ? _c : "");
      if (!oldText)
        return "Error: old_text is required for replace_block mode";
      if (!existing.includes(oldText)) {
        return `Error: Could not find the text to replace. Make sure it matches exactly (including whitespace):
\`\`\`
${oldText}
\`\`\``;
      }
      const updated = existing.replace(oldText, newText);
      await this.app.vault.modify(file, updated);
      await this.indexer.updateFile(file);
      return `\u2705 Replaced block in "${path}" (${Math.abs(newText.length - oldText.length)} chars delta)`;
    }
    if (mode === "full_overwrite") {
      if (this.settings.editPermission !== "full_edit") {
        return 'Error: Full overwrite requires "full_edit" permission in plugin settings.';
      }
      const newContent = String((_d = args.new_content) != null ? _d : "");
      await this.app.vault.modify(file, newContent);
      await this.indexer.updateFile(file);
      return `\u2705 Overwrote "${path}" with ${newContent.length} chars`;
    }
    return `Error: Unknown edit mode "${mode}". Use "replace_block" or "full_overwrite".`;
  }
  async toolCreateNote(args) {
    var _a, _b;
    if (this.settings.editPermission === "read_only") {
      return "Error: Edit permission is set to read-only. Change it in plugin settings.";
    }
    if (this.settings.editPermission === "read_append") {
      return 'Error: Creating notes requires "full_edit" permission in plugin settings.';
    }
    const path = this.validatePath(args.path);
    if (!path)
      return "Error: Invalid or missing path";
    const content = String((_a = args.content) != null ? _a : "");
    const overwrite = Boolean((_b = args.overwrite) != null ? _b : false);
    const existing = this.app.vault.getAbstractFileByPath(path);
    if (existing && !overwrite) {
      return `Error: Note already exists at "${path}". Set overwrite: true to replace it.`;
    }
    if (existing instanceof import_obsidian3.TFile && overwrite) {
      const old = await this.app.vault.read(existing);
      this.pushUndo(path, old, `create/overwrite ${path}`);
      await this.app.vault.modify(existing, content);
    } else {
      const folder = path.contains("/") ? path.substring(0, path.lastIndexOf("/")) : "";
      if (folder) {
        const folderExists = this.app.vault.getAbstractFileByPath(folder);
        if (!folderExists) {
          await this.app.vault.createFolder(folder);
        }
      }
      await this.app.vault.create(path, content);
    }
    const file = this.app.vault.getAbstractFileByPath(path);
    if (file)
      await this.indexer.updateFile(file);
    return `\u2705 Created "${path}" (${content.length} chars)`;
  }
  // ── Helpers ───────────────────────────────────────────────────────────────
  validatePath(raw) {
    if (typeof raw !== "string" || !raw.trim())
      return null;
    const normalized = raw.replace(/\\/g, "/").replace(/\.\.\/|\.\.$/g, "").trim();
    return normalized || null;
  }
  pushUndo(path, previousContent, description) {
    this.undoStack.push({ path, previousContent, description, timestamp: Date.now() });
    if (this.undoStack.length > 20)
      this.undoStack.shift();
  }
};

// src/llm.ts
var LLMClient = class {
  constructor(settings) {
    this.settings = settings;
    this.abortController = null;
  }
  updateSettings(settings) {
    this.settings = settings;
  }
  /** Check if llama.cpp is reachable. Returns model name or throws. */
  async healthCheck() {
    var _a, _b, _c;
    const ctrl = new AbortController();
    const timer = setTimeout(() => ctrl.abort(), 5e3);
    try {
      const res = await fetch(`${this.settings.endpoint}/v1/models`, { signal: ctrl.signal });
      if (!res.ok)
        throw new Error(`HTTP ${res.status}`);
      const data = await res.json();
      return (_c = (_b = (_a = data == null ? void 0 : data.data) == null ? void 0 : _a[0]) == null ? void 0 : _b.id) != null ? _c : "unknown";
    } finally {
      clearTimeout(timer);
    }
  }
  /** Abort the current streaming request */
  abort() {
    var _a;
    (_a = this.abortController) == null ? void 0 : _a.abort();
    this.abortController = null;
  }
  /**
   * Main entry point: run a full turn (possibly multiple tool calls).
   * Yields StreamChunk events to the caller via the onChunk callback.
   */
  async *runTurn(messages, toolExecutor, onChunk) {
    var _a, _b, _c, _d, _e;
    const workingMessages = [...messages];
    let depth = 0;
    while (depth < this.settings.maxToolCallDepth) {
      this.abortController = new AbortController();
      const useTools = this.settings.toolCallingMode === "native" || this.settings.toolCallingMode === "prompt_injection";
      let assistantText = "";
      let toolCalls = [];
      let finishReason = null;
      const body = {
        model: this.settings.model || void 0,
        messages: workingMessages,
        stream: true,
        temperature: this.settings.temperature
      };
      if (this.settings.toolCallingMode === "native") {
        body.tools = TOOL_DEFINITIONS;
        body.tool_choice = "auto";
      }
      let response;
      try {
        response = await fetch(`${this.settings.endpoint}/v1/chat/completions`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(body),
          signal: this.abortController.signal
        });
      } catch (e) {
        if (e.name === "AbortError") {
          onChunk({ type: "done" });
          return;
        }
        onChunk({
          type: "error",
          error: `Connection failed: ${e.message}. Is llama.cpp running at ${this.settings.endpoint}?`
        });
        return;
      }
      if (!response.ok) {
        const text = await response.text();
        onChunk({ type: "error", error: `Server error ${response.status}: ${text}` });
        return;
      }
      if (!response.body) {
        onChunk({ type: "error", error: "No response body from server" });
        return;
      }
      const partialToolCalls = {};
      try {
        const reader = response.body.getReader();
        const decoder = new TextDecoder();
        let buffer = "";
        while (true) {
          const { done, value } = await reader.read();
          if (done)
            break;
          buffer += decoder.decode(value, { stream: true });
          const lines = buffer.split("\n");
          buffer = (_a = lines.pop()) != null ? _a : "";
          for (const line of lines) {
            const trimmed = line.trim();
            if (!trimmed.startsWith("data:"))
              continue;
            const payload = trimmed.slice(5).trim();
            if (payload === "[DONE]") {
              finishReason = finishReason != null ? finishReason : "stop";
              break;
            }
            let chunk;
            try {
              chunk = JSON.parse(payload);
            } catch (e) {
              continue;
            }
            const choice = (_b = chunk.choices) == null ? void 0 : _b[0];
            if (!choice)
              continue;
            if (choice.finish_reason)
              finishReason = choice.finish_reason;
            const delta = choice.delta;
            if (delta.content) {
              assistantText += delta.content;
              onChunk({ type: "token", content: delta.content });
            }
            if (delta.tool_calls) {
              for (const tc of delta.tool_calls) {
                if (!partialToolCalls[tc.index]) {
                  partialToolCalls[tc.index] = { id: (_c = tc.id) != null ? _c : "", name: "", args: "" };
                }
                if ((_d = tc.function) == null ? void 0 : _d.name)
                  partialToolCalls[tc.index].name += tc.function.name;
                if ((_e = tc.function) == null ? void 0 : _e.arguments)
                  partialToolCalls[tc.index].args += tc.function.arguments;
                if (tc.id)
                  partialToolCalls[tc.index].id = tc.id;
              }
            }
          }
        }
      } catch (e) {
        if (e.name === "AbortError") {
          onChunk({ type: "done" });
          return;
        }
        throw e;
      }
      toolCalls = Object.values(partialToolCalls).map((tc) => ({
        id: tc.id || `call_${Date.now()}_${Math.random().toString(36).slice(2)}`,
        type: "function",
        function: { name: tc.name, arguments: tc.args }
      }));
      if (this.settings.toolCallingMode === "prompt_injection" && assistantText && toolCalls.length === 0) {
        const injectionCalls = parseInjectionToolCalls(assistantText);
        if (injectionCalls.length > 0) {
          toolCalls = injectionCalls;
          assistantText = assistantText.replace(/<tool_call>[\s\S]*?<\/tool_call>/g, "").trim();
          finishReason = "tool_calls";
        }
      }
      const assistantMsg = {
        role: "assistant",
        content: assistantText || null,
        ...toolCalls.length > 0 ? { tool_calls: toolCalls } : {}
      };
      workingMessages.push(assistantMsg);
      if (toolCalls.length === 0 || finishReason !== "tool_calls") {
        onChunk({ type: "done" });
        yield workingMessages;
        return;
      }
      for (const tc of toolCalls) {
        const toolName = tc.function.name;
        const toolArgs = tc.function.arguments;
        onChunk({ type: "tool_start", toolName, toolArgs });
        const result = await toolExecutor.execute(toolName, toolArgs);
        onChunk({ type: "tool_end", toolName, toolResult: result });
        workingMessages.push({
          role: "tool",
          tool_call_id: tc.id,
          name: toolName,
          content: result
        });
      }
      depth++;
    }
    onChunk({
      type: "error",
      error: `Max tool call depth (${this.settings.maxToolCallDepth}) exceeded. Stopping.`
    });
    onChunk({ type: "done" });
    yield workingMessages;
  }
};
function parseInjectionToolCalls(text) {
  var _a;
  const calls = [];
  const regex = /<tool_call>\s*([\s\S]*?)\s*<\/tool_call>/g;
  let match;
  while ((match = regex.exec(text)) !== null) {
    try {
      const parsed = JSON.parse(match[1]);
      if (parsed.name) {
        calls.push({
          id: `inj_${Date.now()}_${Math.random().toString(36).slice(2)}`,
          type: "function",
          function: {
            name: parsed.name,
            arguments: JSON.stringify((_a = parsed.arguments) != null ? _a : {})
          }
        });
      }
    } catch (e) {
    }
  }
  return calls;
}

// src/context.ts
function estimateTokens(text) {
  return Math.ceil(text.length / 4);
}
var ContextBuilder = class {
  constructor(indexer, settings) {
    this.indexer = indexer;
    this.settings = settings;
  }
  updateSettings(settings) {
    this.settings = settings;
  }
  /**
   * Build the full system message, including:
   * - Role description + today's date
   * - Vault map (all note paths + tags)
   * - Auto-injected top-N relevant notes (full content)
   * - Tool injection prompt (if mode = prompt_injection)
   * - User-supplied extra instructions
   */
  async buildSystemMessage(userMessage) {
    const budget = this.settings.contextWindowTokens;
    const parts = [];
    const today = new Date().toLocaleDateString("en-US", {
      weekday: "long",
      year: "numeric",
      month: "long",
      day: "numeric"
    });
    parts.push(
      `You are a helpful AI assistant embedded in Obsidian, a personal knowledge management app.
Today is ${today}.

You have full general knowledge and should answer questions normally, just like any capable AI assistant.
In addition, you have special tools that give you access to the user's Obsidian vault (their Markdown notes).
Use vault tools when: the user asks about their notes, wants to search/edit/create notes, or asks something that would benefit from checking their personal knowledge base.
Do NOT use vault tools for general knowledge questions (history, science, language, coding, etc.) \u2014 just answer those directly.
Be concise and helpful. When you do reference vault content, cite the note path.`
    );
    if (this.settings.toolCallingMode === "prompt_injection") {
      parts.push("\n" + TOOL_INJECTION_PROMPT);
    }
    if (this.settings.systemPromptExtra.trim()) {
      parts.push("\n" + this.settings.systemPromptExtra.trim());
    }
    const vaultMap = this.indexer.getVaultMap();
    const vaultMapSection = `
## Vault Map (${this.indexer.noteCount} notes)
The following notes exist in the vault (excluded: ${this.indexer.excludedCount}):
` + vaultMap;
    const baseTokens = estimateTokens(parts.join("\n") + vaultMapSection);
    const remainingBudget = budget - baseTokens - 200;
    const injectedNotes = [];
    if (this.settings.autoInjectNotes > 0 && remainingBudget > 200 && userMessage.trim()) {
      const topNotes = this.indexer.getTopNotes(userMessage, this.settings.autoInjectNotes);
      let usedTokens = 0;
      for (const meta of topNotes) {
        const content = await this.indexer.readNote(meta.path);
        if (!content)
          continue;
        const noteSection = `
### Note: ${meta.path}
${content}`;
        const noteTokens = estimateTokens(noteSection);
        if (usedTokens + noteTokens > remainingBudget)
          break;
        injectedNotes.push(noteSection);
        usedTokens += noteTokens;
      }
    }
    let systemPrompt = parts.join("\n") + vaultMapSection;
    if (injectedNotes.length > 0) {
      systemPrompt += `

## Pre-loaded Notes (auto-selected as relevant to the current query)
` + injectedNotes.join("\n\n");
    }
    return systemPrompt;
  }
  /**
   * Prepend a fresh system message to the conversation history.
   * Replaces any existing system message.
   */
  async prependSystemMessage(messages, userMessage) {
    const systemContent = await this.buildSystemMessage(userMessage);
    const withoutSystem = messages.filter((m) => m.role !== "system");
    return [{ role: "system", content: systemContent }, ...withoutSystem];
  }
};

// src/settings.ts
var import_obsidian4 = require("obsidian");
var DEFAULT_SETTINGS = {
  endpoint: "http://localhost:8080",
  model: "",
  systemPromptExtra: "",
  contextWindowTokens: 32768,
  autoInjectNotes: 3,
  editPermission: "read_append",
  toolCallingMode: "native",
  excludePatterns: ["Private/**", "*.secret.md"],
  maxToolCallDepth: 10,
  showDiffPreview: true,
  diffPreviewThreshold: 200,
  temperature: 0.7
};
var LlamaSettingTab = class extends import_obsidian4.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.addClass("llama-settings");
    containerEl.createEl("h2", { text: "\u{1F999} LLAMA Chat Settings" });
    containerEl.createEl("h3", { text: "\u{1F50C} Connection" });
    new import_obsidian4.Setting(containerEl).setName("LLM Endpoint").setDesc("Base URL of your llama.cpp server (no trailing slash)").addText(
      (text) => text.setPlaceholder("http://localhost:8080").setValue(this.plugin.settings.endpoint).onChange(async (value) => {
        this.plugin.settings.endpoint = value.replace(/\/$/, "");
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Model Name").setDesc("Model identifier to request (leave blank to use server default)").addText(
      (text) => text.setPlaceholder("auto-detect").setValue(this.plugin.settings.model).onChange(async (value) => {
        this.plugin.settings.model = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Temperature").setDesc("Sampling temperature (0 = deterministic, 1 = creative, 2 = chaotic)").addSlider(
      (slider) => slider.setLimits(0, 2, 0.05).setValue(this.plugin.settings.temperature).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.temperature = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "\u{1F9E0} Context" });
    new import_obsidian4.Setting(containerEl).setName("Context Window (tokens)").setDesc("Max tokens to use for context. Match your model's context size.").addSlider(
      (slider) => slider.setLimits(1024, 131072, 1024).setValue(this.plugin.settings.contextWindowTokens).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.contextWindowTokens = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Auto-inject notes count").setDesc("Number of top-ranked relevant notes auto-injected into each message").addSlider(
      (slider) => slider.setLimits(0, 10, 1).setValue(this.plugin.settings.autoInjectNotes).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.autoInjectNotes = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Extra system prompt").setDesc("Additional instructions appended to the base system prompt").addTextArea(
      (text) => text.setPlaceholder("You prefer short, concise answers...").setValue(this.plugin.settings.systemPromptExtra).onChange(async (value) => {
        this.plugin.settings.systemPromptExtra = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "\u{1F512} Vault Permissions" });
    new import_obsidian4.Setting(containerEl).setName("Edit permission level").setDesc("Controls what the LLM is allowed to do in your vault").addDropdown(
      (drop) => drop.addOption("read_only", "\u{1F50D} Read only \u2014 search & read notes").addOption("read_append", "\u270F\uFE0F Read + Append \u2014 add content to notes").addOption("full_edit", "\u26A0\uFE0F Full edit \u2014 create, modify, overwrite").setValue(this.plugin.settings.editPermission).onChange(async (value) => {
        this.plugin.settings.editPermission = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "\u{1F6E0}\uFE0F Tool Calling" });
    new import_obsidian4.Setting(containerEl).setName("Tool calling mode").setDesc(
      "Native: OpenAI-style function calling (requires compatible model). Prompt injection: works with any model. Disabled: no vault tools."
    ).addDropdown(
      (drop) => drop.addOption("native", "\u26A1 Native function calling").addOption("prompt_injection", "\u{1F4DD} Prompt injection (universal)").addOption("disabled", "\u{1F6AB} Disabled").setValue(this.plugin.settings.toolCallingMode).onChange(async (value) => {
        this.plugin.settings.toolCallingMode = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Max tool call depth").setDesc("Maximum number of consecutive tool calls per turn (prevents infinite loops)").addSlider(
      (slider) => slider.setLimits(1, 20, 1).setValue(this.plugin.settings.maxToolCallDepth).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.maxToolCallDepth = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "\u{1F648} Privacy" });
    new import_obsidian4.Setting(containerEl).setName("Exclude patterns").setDesc("Glob patterns for notes/folders to hide from the LLM (comma-separated)").addTextArea(
      (text) => text.setPlaceholder("Private/**, Diary/**, *.secret.md").setValue(this.plugin.settings.excludePatterns.join(", ")).onChange(async (value) => {
        this.plugin.settings.excludePatterns = value.split(",").map((p) => p.trim()).filter(Boolean);
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "\u{1F6E1}\uFE0F Edit Safety" });
    new import_obsidian4.Setting(containerEl).setName("Show diff preview").setDesc("Show a change preview in chat before applying edits").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showDiffPreview).onChange(async (value) => {
        this.plugin.settings.showDiffPreview = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Diff preview threshold (chars)").setDesc("Only show diff preview when the edit changes more than this many characters").addSlider(
      (slider) => slider.setLimits(0, 2e3, 50).setValue(this.plugin.settings.diffPreviewThreshold).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.diffPreviewThreshold = value;
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/main.ts
var LlamaPlugin = class extends import_obsidian5.Plugin {
  constructor() {
    super(...arguments);
    this.indexRebuildTimer = null;
  }
  // ── Lifecycle ──────────────────────────────────────────────────────────────
  async onload() {
    if (import_obsidian5.Platform.isMobile) {
      this.addRibbonIcon("message-circle", "LLAMA Chat (desktop only)", () => {
        new import_obsidian5.Notice("LLAMA Chat requires a desktop environment to reach your local LLM.");
      });
      return;
    }
    await this.loadSettings();
    this.initServices();
    this.registerView(LLAMA_CHAT_VIEW_TYPE, (leaf) => new ChatView(leaf, this));
    this.addRibbonIcon("message-circle", "Open LLAMA Chat", () => this.activateView());
    this.addCommand({
      id: "open-llama-chat",
      name: "Open LLAMA Chat sidebar",
      callback: () => this.activateView()
    });
    this.addCommand({
      id: "llama-reindex-vault",
      name: "LLAMA Chat: Re-index vault",
      callback: () => this.rebuildIndex()
    });
    this.addSettingTab(new LlamaSettingTab(this.app, this));
    this.buildIndexInBackground();
    this.registerVaultEvents();
  }
  onunload() {
    this.app.workspace.detachLeavesOfType(LLAMA_CHAT_VIEW_TYPE);
    if (this.indexRebuildTimer)
      clearTimeout(this.indexRebuildTimer);
  }
  // ── Settings ───────────────────────────────────────────────────────────────
  async loadSettings() {
    var _a;
    const data = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, (_a = data == null ? void 0 : data.settings) != null ? _a : {});
  }
  async saveSettings() {
    var _a;
    const existing = (_a = await this.loadData()) != null ? _a : {};
    await this.saveData({ ...existing, settings: this.settings });
    if (this.llmClient)
      this.llmClient.updateSettings(this.settings);
    if (this.toolExecutor)
      this.toolExecutor.updateSettings(this.settings);
    if (this.contextBuilder)
      this.contextBuilder.updateSettings(this.settings);
    if (this.indexer)
      this.indexer.updateSettings(this.settings);
  }
  // ── Services ───────────────────────────────────────────────────────────────
  initServices() {
    this.indexer = new VaultIndexer(this.app, this.settings);
    this.llmClient = new LLMClient(this.settings);
    this.toolExecutor = new ToolExecutor(this.app, this.indexer, this.settings);
    this.contextBuilder = new ContextBuilder(this.indexer, this.settings);
  }
  // ── Vault Indexing ─────────────────────────────────────────────────────────
  async buildIndexInBackground() {
    var _a;
    const data = await this.loadData();
    const savedIndex = (_a = data == null ? void 0 : data.index) != null ? _a : null;
    try {
      await this.indexer.build(savedIndex);
      await this.persistIndex();
      console.log(`[LLAMA Chat] Vault indexed: ${this.indexer.noteCount} notes`);
    } catch (e) {
      console.error("[LLAMA Chat] Indexing error:", e);
    }
  }
  async persistIndex() {
    var _a;
    const existing = (_a = await this.loadData()) != null ? _a : {};
    await this.saveData({ ...existing, index: this.indexer.getSerializable() });
  }
  async rebuildIndex() {
    new import_obsidian5.Notice("\u{1F999} Re-indexing vault\u2026");
    await this.indexer.build(null);
    await this.persistIndex();
    new import_obsidian5.Notice(`\u{1F999} Vault indexed: ${this.indexer.noteCount} notes`);
  }
  // ── Vault Event Handlers ───────────────────────────────────────────────────
  registerVaultEvents() {
    this.registerEvent(
      this.app.vault.on("create", async (file) => {
        if (file instanceof import_obsidian5.TFile && file.extension === "md") {
          await this.indexer.updateFile(file);
          this.schedulePersist();
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("modify", async (file) => {
        if (file instanceof import_obsidian5.TFile && file.extension === "md") {
          await this.indexer.updateFile(file);
          this.schedulePersist();
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("delete", (file) => {
        if (file instanceof import_obsidian5.TFile && file.extension === "md") {
          this.indexer.removeFile(file.path);
          this.schedulePersist();
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("rename", async (file, oldPath) => {
        if (file instanceof import_obsidian5.TFile && file.extension === "md") {
          await this.indexer.renameFile(file, oldPath);
          this.schedulePersist();
        }
      })
    );
  }
  /** Debounce index persistence to avoid writing on every keystroke */
  schedulePersist() {
    if (this.indexRebuildTimer)
      clearTimeout(this.indexRebuildTimer);
    this.indexRebuildTimer = setTimeout(() => this.persistIndex(), 5e3);
  }
  // ── View Management ────────────────────────────────────────────────────────
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(LLAMA_CHAT_VIEW_TYPE);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getRightLeaf(false);
      if (leaf)
        await leaf.setViewState({ type: LLAMA_CHAT_VIEW_TYPE, active: true });
    }
    if (leaf)
      workspace.revealLeaf(leaf);
  }
};
